server:
  port: 8595

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smukk9/blog-config-external.git
          search-paths:
          - blog-*
          force-pull: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8766/eureka}